<a href="https://colab.research.google.com/github/anwarshaik1/Machine-Learning-/blob/main/ML_Lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#1 Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to
# compute the mean and variance of the elements present in the array.

def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

# Example usage:
N = 5  # Number of dimensions
vector = np.random.rand(N)  # Generating a random feature vector of size N
print("Vector:",vector)
mean, variance = compute_mean_and_variance(vector)
print("Mean of the vector:", mean)
print("Variance of the vector:", variance)


Vector: [0.25078657 0.46514657 0.03007253 0.92022785 0.33648306]
Mean of the vector: 0.40054331618573646
Variance of the vector: 0.0876050003988495


In [9]:
#2 Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to
# compute the Covariance between them.

import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.cov(vector1, vector2, bias=True)[0][1]
    return covariance

# Example usage:
M = 5  # Number of dimensions
N = 100  # Number of samples
# Generating two random feature vectors of size M
vector1 = np.random.rand(1, M)
vector2 = np.random.rand(1, M)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
covariance = compute_covariance(vector1, vector2)
print("Covariance between the two vectors:", covariance)

Vector 1: [[0.65211167 0.00585239 0.24413138 0.79310686 0.82812672]]
Vector 2: [[0.32703587 0.53689923 0.33616148 0.12932255 0.554628  ]]
Covariance between the two vectors: -0.018094335264608123


In [10]:
#3 Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

import numpy as np

def compute_correlation(vector1, vector2):
    correlation = np.corrcoef(vector1, vector2)[0, 1]
    return correlation

# Example usage:
N = 5  # Number of dimensions
vector1 = np.random.rand(N)  # Generating a random vector of size N
vector2 = np.random.rand(N)  # Generating another random vector of size N
print("Vector 1:", vector1)
print("Vector 2:", vector2)
correlation = compute_correlation(vector1, vector2)
print("Correlation between vector 1 and vector 2:", correlation)


Vector 1: [0.56454992 0.25688111 0.3408951  0.55559978 0.66748966]
Vector 2: [0.07049754 0.28135195 0.98835296 0.50342758 0.73750983]
Correlation between vector 1 and vector 2: -0.04205257761093297


In [11]:
#4 Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th
#entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and
#correlation matrix.

import numpy as np

def compute_covariance_matrix(feature_matrix):
    covariance_matrix = np.cov(feature_matrix)
    return covariance_matrix

def compute_correlation_matrix(feature_matrix):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix

# Example usage:
M = 3  # Number of dimensions/features
N = 5  # Number of samples
feature_matrix = np.random.rand(M, N)  # Generating a random feature matrix of size MxN
print("Feature matrix:")
print(feature_matrix)
covariance_matrix = compute_covariance_matrix(feature_matrix)
print("\nCovariance matrix:")
print(covariance_matrix)
correlation_matrix = compute_correlation_matrix(feature_matrix)
print("\nCorrelation matrix:")
print(correlation_matrix)


Feature matrix:
[[0.88773485 0.37159416 0.1392242  0.05977958 0.77555789]
 [0.87545743 0.17837621 0.36654313 0.23275427 0.18737471]
 [0.15366768 0.92987804 0.3137832  0.38331889 0.00810089]]

Covariance matrix:
[[ 0.13813722  0.05785637 -0.06108421]
 [ 0.05785637  0.0860973  -0.03807268]
 [-0.06108421 -0.03807268  0.12345536]]

Correlation matrix:
[[ 1.          0.5305191  -0.46775521]
 [ 0.5305191   1.         -0.36928677]
 [-0.46775521 -0.36928677  1.        ]]
